name: test-index-only

on:
  pull_request:
    paths:
      - src/index/index.py
  workflow_dispatch:

jobs:
  test-index-only:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      - name: Run index test
        run: |
          python -m pytest --cov=src/index --cov-report=xml tests/unit/index

      - name: Upload all coverage
        uses: codecov/codecov-action@v2
        with:
          files: coverage.xml
          fail_ci_if_error: false
          verbose: true
          flags: index
